version: 2
jobs:
  build:
    docker:
      - image: cirlceci/node:7.10
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
      - run: echo "ALL GOOD IN THE HOOD"