version: 2
jobs:
  build:
    docker:
      - image: circleci/node
        environment:
          NODE_ENV: testing
          PGHOST: 127.0.0.1
          PGUSER: ubuntu

      - image: circleci/postgres
        environment:
          POSTGRES_DB: teststar
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: root
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      # - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
